sonar.projectKey=python_metrics_project
sonar.projectName=Python Metrics Project
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://localhost:9000
sonar.login=squ_41346058a51f0786b66af2cdcdd88ca22408325e